apiVersion: v0.1
workloads:
  important:
    runtime: podman
    agent: agent_B
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5001:5001", "-e", "PASSWORD=admin"]

  throughout:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        important: ADD_COND_RUNNING
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5002:5001", "-e", "PASSWORD=admin"]

  if:
    runtime: podman
    agent: agent_C
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        important: ADD_COND_FAILED
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5003:5001", "-e", "PASSWORD=admin"]

  hair:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        important: ADD_COND_FAILED
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5004:5001", "-e", "PASSWORD=admin"]

  matter:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        important: ADD_COND_FAILED
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5005:5001", "-e", "PASSWORD=admin"]

  impact:
    runtime: podman
    agent: agent_C
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        throughout: ADD_COND_FAILED
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5006:5001", "-e", "PASSWORD=admin"]

  lawyer:
    runtime: podman
    agent: agent_C
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        important: ADD_COND_RUNNING
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5007:5001", "-e", "PASSWORD=admin"]

  product:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        matter: ADD_COND_FAILED
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5008:5001", "-e", "PASSWORD=admin"]

  room:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        matter: ADD_COND_RUNNING
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5009:5001", "-e", "PASSWORD=admin"]

  build:
    runtime: podman
    agent: agent_B
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        lawyer: ADD_COND_FAILED
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5010:5001", "-e", "PASSWORD=admin"]

  choice:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        impact: ADD_COND_RUNNING
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5011:5001", "-e", "PASSWORD=admin"]

  ten:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        hair: ADD_COND_FAILED
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5012:5001", "-e", "PASSWORD=admin"]

  life:
    runtime: podman
    agent: agent_B
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        if: ADD_COND_RUNNING
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5013:5001", "-e", "PASSWORD=admin"]

  eat:
    runtime: podman
    agent: agent_C
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        matter: ADD_COND_FAILED
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5014:5001", "-e", "PASSWORD=admin"]

  herself:
    runtime: podman
    agent: agent_C
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        eat: ADD_COND_FAILED
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5015:5001", "-e", "PASSWORD=admin"]

  ball:
    runtime: podman
    agent: agent_B
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Passenger 
      - key: Running in
        value: Infotainment
    dependencies:
        room: ADD_COND_RUNNING
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5016:5001", "-e", "PASSWORD=admin"]