apiVersion: v0.1
workloads:
  workload_a:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Driver
      - key: Running in
        value: AC Unit
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5001:5001", "-e", "PASSWORD=admin"]

  workload_b:
    runtime: podman
    agent: agent_B
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Front Passenger
      - key: Running in
        value: Infotainment
    dependencies:
      workload_a: ADD_COND_RUNNING
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5002:5001"]


  watch_dog:
    runtime: podman
    agent: agent_C
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Cloud Service
      - key: Running in
        value: Drivetrain
    dependencies:
      workload_b: ADD_COND_FAILED
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5003:5001"]

