apiVersion: v0.1
workloads:
  ank_dashboard_A:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Driver
      - key: Running in
        value: AC Unit
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5001:5001"]

  ank_dashboard_B:
    runtime: podman
    agent: agent_B
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Front Passenger
      - key: Running in
        value: Infotainment
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5002:5001"]

  ank_dashboard_C:
    runtime: podman
    agent: agent_C
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    dependencies:
      ank_startup_cond_C: ADD_COND_RUNNING
    tags:
      - key: Started by
        value: Cloud Service
      - key: Running in
        value: Drivetrain
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5003:5001"]

  ank_dashboard_D:
    runtime: podman
    agent: agent_D
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    dependencies:
      ank_startup_cond_D: ADD_COND_FAILED
    tags:
      - key: Started by
        value: Driver
      - key: Running in
        value: Infotainment
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5004:5001"]


  ank_startup_cond_D:
    runtime: podman
    agent: agent_D
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    dependencies:
    commandArgs: [ "-c", "sleep 10; exit 1" ]
    tags:
      - key: Started by
        value: Driver
      - key: Running in
        value: Infotainment
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5005:5001"]

