apiVersion: v0.1
workloads:
  ank_dashboard_A:
    runtime: podman
    agent: agent_A
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Felix
      - key: Run in
        value: AC Unit
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5001:5001"]

  ank_dashboard_B:
    runtime: podman
    agent: agent_B
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Hendrik
      - key: Run in
        value: Infotainment
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5002:5001"]

  ank_dashboard_C:
    runtime: podman
    agent: agent_C
    restart: true
    updateStrategy: AT_LEAST_ONCE
    accessRights:
      allow: []
      deny: []
    restartPolicy: NEVER
    tags:
      - key: Started by
        value: Ömür
      - key: Run in
        value: Drivetrain
    runtimeConfig: |
      image: dashboard:0.0
      commandOptions: ["-p", "5003:5001"]
